destination: docs

title: Jamie on Software
email: jamie@jamierumbelow.net
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: https://jamieonsoftware.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jamierumbelow
github_username: jamierumbelow

paginate: 10
paginate_path: "/page:num/"

timezone: Europe/London

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate

jekyll-archives:
  enabled: [tags]
  layout: tag
  permalinks:
    tag: "/:name/"
